[package]
name = "quantum-werewolf"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]

[lib]
name = "quantum_werewolf"
path = "src/lib.rs"

[[bin]]
name = "qww"
doc = false
test = false
bench = false

[dependencies]
itertools = "*"
rand = "*"
